### PR TITLE
Added instructions for WSL2 integration

### PR DESCRIPTION
**Pull request by LukeLavan**
Getting this set up using WSL required a few extra steps, which I detail on a new html page referenced from the 'Getting Started' page.

### CODE REVIEW

**Comment by LukeLavan** [comment]
I took a hands-off approach with `gettingStarted.html`, since the rest of the steps are practically the same. The steps/errors documented in `wslSteps.html` are what I ran into when getting started on my machine - hopefully this is reflective for other WSL users.

Thanks @limh0228 for [this](https://docs.docker.com/docker-for-windows/wsl/) link as well.

**Comment by limh0228** [comment]
Hey this looks great! Thanks for adding my changes for me (I went ahead and closed my PR since it's redundant now).
I would just add one thing: since line numbers may change in the future, I would just say: "in the file docker-compose.yaml, Change these two constants under database environment and volumes configurations"

**Comment by LukeLavan** [comment]
> I would just add one thing: since line numbers may change in the future, I would just say: "in the file docker-compose.yaml, Change these two constants under database environment and volumes configurations"

Good point, my latest push takes this advice and makes it more clear where these edits should take place. Thanks!

**Review by huss — APPROVED** [review]
This looks good. I appreciate the update of Windows directions.

**Pull request merged**
