### PR TITLE
Updated Images

### PR DESCRIPTION
**Pull request by LucasFares**
Took new screenshots to show progress. Removed OEDGroupsSecondFloors.png as all information it conveyed is now included in OEDGroupsAllFloors.png.

### CODE REVIEW

**Review by huss — COMMENTED** [review]
Since comments is on files it seems they cannot be attached to that file so:
* The data has less range of dates. Was this done with server data? I think that would be nicer and better since what people see on the demo site.
* I think we should show a meter and a group in the compare. This demonstrates it can do more than one now and the generality.
* The groups editing cuts off third floors but are selected. I think it should be included.
* We need to move baselining to a 0.3 feature since it is not done yet.

**Comment by SophiaFares** [comment]
I'll fix the smaller date range as soon as I get some historical data. I'll also add a compare group photo. I'm not sure how to go about adding the third floor into the screenshot as it does not fit on the screen. Zooming out does not seem like the correct solution. I could simply not select it? As far as showcasing features it does nothing. Baselining is referred to as  a 0.3 feature on the release page (see PR #3) and the features page claims that it is coming soon. I can't find any other mentions.

**Comment by huss** [comment]
For all the data it might be easier/best to get it from the server. We have Docker working so changing the BC version should be easy.
If the third floor does not fit then lets not highlight it.
I think the features page should be production items. The plans/future pages (or whatever they become) should be for features that are coming. So, I wanted to move baselining off the features page for now and put it on the other page.

**Comment by SophiaFares** [comment]
I address the baseline in PR #3. I'll update the rest of the pictures once 0.2 is rolled out to a Beloit instance.

**Comment by huss** [comment]
I'm going to merge this pull request so we have newer images. We still need to update when the new version has the BC data. One other small item is that the old image of the line chart showed the hover info when the curser is over a line on the graph. It might be nice to include in the updated figures.

**Comment by SophiaFares** [comment]
I noticed that but didn't want my cursor in the screenshot. If you think the hover info is worth it I'll incorporate that into the updated image.

**Comment by huss** [comment]
I did it in one image to show it would work but not others to avoid
cluttering it too much. I tried to pick a spot where it did not obscure
much.

**Pull request merged**
